# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x090c0dff
rootcolor = 0x151a1cff
bordercolor = 0x336e70ff
focuscolor = 0xff4d4dff
maximizescreencolor = 0x2a5a5cff
urgentcolor = 0xff0000ff
scratchpadcolor = 0x56b6c2ff
globalcolor = 0x9a0000ff
overlaycolor = 0x12393aff
