color0 #151a1c
color1 #ff0000
color2 #3ecc61
color3 #ccc03e
color4 #ff4d4d
color5 #2a5a5c
color6 #56b6c2
color7 #e1e8e6
color8 #0b3335
color9 #ff1919
color10 #62f285
color11 #f2e662
color12 #ff6666
color13 #488082
color14 #7edce8
color15 #ffffff
background #151a1c
selection_foreground #151a1c
cursor #ff4d4d
cursor_text_color #151a1c
foreground #e1e8e6
selection_background #ff4d4d
active_border_color #ff4d4d
inactive_border_color #2a5a5c

active_tab_foreground   #151a1c
active_tab_background   #ff4d4d
inactive_tab_foreground #b0bdba
inactive_tab_background #0b3335
cursor_trail_color      #b0bdba
